[package]
name = "auth-service"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = { workspace = true, features = ["std"] }
axum = { workspace = true }
axum-extra = { workspace = true, features = ["cookie"] }
chrono = { workspace = true }
color-eyre = { workspace = true }
dotenvy = { workspace = true }
jsonwebtoken = { workspace = true, features = ["aws_lc_rs"] }
lazy_static = { workspace = true }
rand = { workspace = true }
redis = { workspace = true, features = ["tokio-comp"] }
reqwest = { workspace = true, default-features = false, features = ["json", "rustls-tls", "cookies"] }
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio-rustls", "postgres", "migrate"]}
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower-http = { workspace = true, features = ["fs", "cors", "trace"] }
tracing = { workspace = true }
tracing-error = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "registry"] }
utoipa = { workspace = true, features = ["axum_extras", "uuid"] }
utoipa-rapidoc = { workspace = true, features = ["axum"] }
uuid = { workspace = true, features = ["v4", "serde"] }
validator = { workspace = true, features = ["derive"] }

[dev-dependencies]
test-helpers = { path = "../test-helpers"}
fake = { workspace = true }
quickcheck = { workspace = true }
quickcheck_macros = { workspace = true }
wiremock = { workspace = true }